package com.jiteen.claims.claim.application.dto.response;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.ToString;

import java.time.LocalDateTime;
import java.util.List;
import java.util.UUID;

/**
 * Data Transfer Object (DTO) representing the outgoing REST API response payload
 * for an AI analysis result record associated with an insurance claim.
 *
 * <p>
 * This class exposes the structured intelligence generated by the AI Processing
 * Service to claim officers and administrative consumers through the Claim Service
 * REST API. It includes risk scoring, fraud detection outputs, extracted metadata,
 * and processing recommendations, providing a comprehensive decision-support view.
 * </p>
 *
 * @author Jiteen
 * @version 1.0
 * @since Java 21
 */
@Getter
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ToString
public class AiAnalysisResultResponse {

    /**
     * Unique identifier of the AI analysis result record.
     */
    private UUID id;

    /**
     * Identifier of the parent insurance claim for which this analysis was performed.
     */
    private UUID claimId;

    /**
     * AI-generated narrative summary of the claim context, extracted information,
     * and overall assessment for claim officer review.
     */
    private String summary;

    /**
     * Numerical risk score on a 0–100 scale.
     * {@code 0–30} = Low Risk; {@code 31–70} = Medium Risk; {@code 71–100} = High Risk.
     */
    private Integer riskScore;

    /**
     * Human-readable risk category classification derived from the risk score value.
     */
    private String riskCategory;

    /**
     * AI-generated processing recommendation for claim officers.
     */
    private String recommendedAction;

    /**
     * Ordered list of fraud indicator descriptions detected during automated
     * document analysis and pattern matching workflows.
     */
    private List<String> fraudIndicators;

    /**
     * Policy number extracted from claim documents via OCR analysis.
     */
    private String policyNumber;

    /**
     * Claim amount figure extracted from supporting documentation.
     */
    private Double claimAmountExtracted;

    /**
     * Incident date extracted from supporting documents by the AI model.
     */
    private LocalDateTime incidentDateExtracted;

    /**
     * Customer name as extracted from claim documents via OCR.
     */
    private String customerNameExtracted;

    /**
     * List of document types identified as missing or incomplete during
     * the AI document validation pass.
     */
    private List<String> missingDocuments;

    /**
     * Timestamp at which the AI Processing Service completed its analysis.
     */
    private LocalDateTime processedAt;

    /**
     * Audit timestamp denoting when this analysis result record was first
     * persisted within the Claim Service.
     */
    private LocalDateTime createdAt;
}
